### PR TITLE
Fix same-day event creation with proper timezone handling

### LINKED ISSUE #179: Relax "future" date/time restriction
If I'd like to create an event in the same day, but later (say right now it's 1pm, and I'd like to create an event today at 2pm), I get an error (even though technically it is in the future):

```
Please fix these errors:

    Start time must be in the future.
```

Could you please relax the restriction (for example, to only that the unix time or minutes is greater than the current one, instead of the full day)?

Thank you - I really like this app including the uncluttered, minimalist design! It helps me keep my train of thought and is calming to my mind (unlike other proprietary event hosting platforms out there full of toxic "growth hacks"), not to mention the privacy and freedom benefits too!

### PR DESCRIPTION
**Pull request by realies**
## Summary
- Fixed the date/time validation to use the event's timezone when checking if the start time is in the future
- Previously, `datetime-local` input values were parsed with `new Date()` which used the server's timezone, causing valid same-day events to be rejected
- Now uses `moment.tz()` to properly interpret dates in the event's specified timezone

## Test plan
- [x] Tested in Docker that creating an event 1 hour from now succeeds
- [x] Tested in Docker that creating an event in the past still fails with "Start time must be in the future"
- [x] All 13 existing Cypress tests pass

Fixes #179

### CODE REVIEW

File: src/util/validation.ts [hunk 1]
```diff
@@ -88,27 +88,36 @@ const validateUrl = (url: string) => {
...
-  if (moment(start).isAfter(moment(end))) {
+export const validateEventTime = (
+  start: string,
+  end: string,
+  timezone: string,
+): Error | boolean => {
+  // Parse the datetime-local values in the event's timezone
+  const startMoment = moment.tz(start, timezone);
+  const endMoment = moment.tz(end, timezone);
+  const now = moment();
```
Comment (raphaelkabo) [inline src/util/validation.ts]: Does `moment()` need to be set in the local timezone too? Otherwise it would default to the server zone?
